### PR TITLE
Lint packages

### PR DESCRIPTION
**Pull request by nick-bisonai**
# Description

missed linting has been done, add missing `eslintrc` file to monitor

following up https://github.com/Bisonai/orakl/pull/979

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by bayram98 — APPROVED** [review]
LGTM!

**Comment by martinkersner** [comment]
@nick-bisonai What configuration do you follow? I think we should use the one we already have. Every package should have a `.prettierrc`  (e.g. https://github.com/Bisonai/orakl/blob/master/vrf/.prettierrc) which defines how to format code.

**Comment by nick-bisonai** [comment]
> @nick-bisonai What configuration do you follow? I think we should use the one we already have. Every package should have a `.prettierrc` (e.g. https://github.com/Bisonai/orakl/blob/master/vrf/.prettierrc) which defines how to format code.

I ran `yarn lint --fix` from each packages, shouldn't that apply `.prettierrc` format rules?

**Comment by martinkersner** [comment]
> > @nick-bisonai What configuration do you follow? I think we should use the one we already have. Every package should have a `.prettierrc` (e.g. https://github.com/Bisonai/orakl/blob/master/vrf/.prettierrc) which defines how to format code.
> 
> I ran `yarn lint --fix` from each packages, shouldn't that apply `.prettierrc` format rules?

Linter and prettier are a bit different. When I run `yarn lint --fix` it does not have impact you do, but `.prettierrc` is taken by editor.

**Comment by nick-bisonai** [comment]
> > > @nick-bisonai What configuration do you follow? I think we should use the one we already have. Every package should have a `.prettierrc` (e.g. https://github.com/Bisonai/orakl/blob/master/vrf/.prettierrc) which defines how to format code.
> > 
> > 
> > I ran `yarn lint --fix` from each packages, shouldn't that apply `.prettierrc` format rules?
> 
> Linter and prettier are a bit different. When I run `yarn lint --fix` it does not have impact you do, but `.prettierrc` is taken by editor.

I don't understand why it's acting differently
I'll google this and try to find solution.

**Comment by nick-bisonai** [comment]
I guess it happened because I unified eslint versions during the monorepo implementation and somehow the settings were mixed up.

sorry for confusion, I'll close this PR

eslint didn't work without unifying all the versions for each workspaces, so I updated eslint versions which had lower versions

**Pull request closed without merging**
