### PR TITLE
adapter test script

### PR DESCRIPTION
**Pull request by nick-bisonai**
# Description

adds script to quickly test data fetching, reducing, and aggregating in local environment with adapter json file.

for example, call
```
npx ts-node ./src/tools/run-adapter.ts ./ada-usdt.adapter.json
```
then you can get the results from terminal. json file should be inside `tools` folder

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by martinkersner — APPROVED** [review]
LGTM! Can you please explain this functionality briefly in README so people can easily discover this feature? 🙏

**Comment by nick-bisonai** [comment]
> LGTM! Can you please explain this functionality briefly in README so people can easily discover this feature? 🙏

@martinkersner 
I've added short description in ./fetcher/README.md

**Comment by martinkersner** [comment]
> > LGTM! Can you please explain this functionality briefly in README so people can easily discover this feature? 🙏
> 
> @martinkersner I've added short description in ./fetcher/README.md

Thank you! Just a suggestion for next time, it would be nice to be more formal when writing documentation. Starting a sentence with capital letter and end with period (`.`). 🚀

**Comment by nick-bisonai** [comment]
> > > LGTM! Can you please explain this functionality briefly in README so people can easily discover this feature? 🙏
> > 
> > 
> > @martinkersner I've added short description in ./fetcher/README.md
> 
> Thank you! Just a suggestion for next time, it would be nice to be more formal when writing documentation. Starting a sentence with capital letter and end with period (`.`). 🚀

Thank you for pointing out. I have modified README.md as you've suggested

**Comment by martinkersner** [comment]
> > > > LGTM! Can you please explain this functionality briefly in README so people can easily discover this feature? 🙏
> > > 
> > > 
> > > @martinkersner I've added short description in ./fetcher/README.md
> > 
> > 
> > Thank you! Just a suggestion for next time, it would be nice to be more formal when writing documentation. Starting a sentence with capital letter and end with period (`.`). 🚀
> 
> Thank you for pointing out. I have modified README.md as you've suggested

Great! Let's merge!

**Pull request merged**
