### PR TITLE
Integrate .env of admin page with Dockerfile

### LINKED ISSUE #756: Integrate .env of admin page with Dockerfile

### PR DESCRIPTION
**Pull request by jay-bisonai**
# Description
* Dockerfile need the external IP addresses of the monitor and delegator service as arguments when it run.
* When executed `Create docker image workflow for Admin page` would deploy two images, CYPRESS and BAOBAB

Fixes #756 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [x] Should publish Docker image

### CODE REVIEW

**Review by joseph-bisonai — APPROVED** [review]
LGTM!.
After change api url, you can merge and build image

**Comment by joeybisonai** [comment]
LGTM :)

**Comment by jay-bisonai** [comment]
> LGTM :)

Thank you for comment, Can you approve it?

**Review by joseph-bisonai — COMMENTED** [review]
LGTM!

**Review by bayram98 — APPROVED** [review]
LGTM!

**Pull request merged**
