### PR TITLE
(Delegator) Remove tx store related functionalities

### PR DESCRIPTION
**Pull request by nick-bisonai**
# Description

Remove unused transaction store & read functionalities from delegator
checked it running through local docker-compose

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by martinkersner — COMMENTED** [review]
@nick-bisonai I know that I suggested this as a way to tackle memory leak issue, but we have to understand the consequences. We won't be able to see detailed information about delegator in Grafana. Do you think it is okay to operate it without delegator metrics?

**Comment by nick-bisonai** [comment]
> @nick-bisonai I know that I suggested this as a way to tackle memory leak issue, but we have to understand the consequences. We won't be able to see detailed information about delegator in Grafana. Do you think it is okay to operate it without delegator metrics?

I'll look further into this

**Comment by nick-bisonai** [comment]
possibly migrating whole project into golang is better solution, if caver js can be ported

**Comment by nick-bisonai** [comment]
fixing by rewriting code into golang and removing `Prisma`

**Pull request closed without merging**
