### PR TITLE
Restructure foundry contract directory

### PR DESCRIPTION
**Pull request by KelvinThai**
# Description

The new folder structure;
contract/v0.1
contract/v0.2

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by nick-bisonai — COMMENTED** [review]
Can you also double check if there should be some updates in dockerfiles? last time once there was an update I had to make multiple PRs to fix build issues

reference)
https://github.com/Bisonai/orakl/pull/1124
https://github.com/Bisonai/orakl/pull/1128
https://github.com/Bisonai/orakl/pull/1100

**Comment by KelvinThai** [comment]
> Can you also double check if there should be some updates in dockerfiles? last time once there was an update I had to make multiple PRs to fix build issues
> 
> reference) #1124 #1128 #1100

Docker file built successfully, Please review this again

**Comment by nick-bisonai** [comment]
> > Can you also double check if there should be some updates in dockerfiles? last time once there was an update I had to make multiple PRs to fix build issues
> > reference) #1124 #1128 #1100
> 
> Docker file built successfully, Please review this again

have you tried to run it? when I tried to docker-compose up it didn't work
image
if you think you can't fix it, I'll try to look into this together

**Comment by nick-bisonai** [comment]
I'll approve once I check it running

**Comment by KelvinThai** [comment]
let me try to fix it from my end first. Thank you!

**Comment by nick-bisonai** [comment]
> let me try to fix it from my end first. Thank you!

im assuming i had wrong configuration I'll double check from my side too

**Comment by KelvinThai** [comment]
I think you should check dockerfiles/local-data-feed/tmp/updated-btc-usdt.aggregator.json

**Comment by nick-bisonai** [comment]
> I think you should check dockerfiles/local-data-feed/tmp/updated-btc-usdt.aggregator.json

no it's still not working, please check if following command is running
```
docker-compose -f docker-compose.local-data-feed.yaml up
```

**Review by nick-bisonai — APPROVED** [review]
lgtm!

**Pull request merged**
