### PR TITLE
foundry vscode integration settings

### PR DESCRIPTION
**Pull request by Intizar-T**
# Description

- add remappings.txt for vscode intellisense (wont see bunch of red squiggly lines during development)
- add format on save with forge for .sol files and prettier for all other files

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Comment by martinkersner** [comment]
I see that some projects include these kind of editor specific settings to projects, but I am not sure whether it is something to follow 🤔

**Comment by nick-bisonai** [comment]
I pulled this branch and tried in my local laptop but i don't think the settings are applied

**Comment by Intizar-T** [comment]
> I pulled this branch and tried in my local laptop but i don't think it's working, I'll try again tmr with office laptop

vscode is a bit pain in the ass. So you need to open v0.2 in a new vscode window/instance to be able to apply project/workspace level vscode settings. The settings didn't work me either when I opened the whole orakl monorepo but they worked when I opened v0.2 separately.

**Review by nick-bisonai — APPROVED** [review]
lgtm!

**Pull request merged**
