### PR TITLE
removed magic constant

### PR DESCRIPTION
**Pull request by KelvinThai**
# Description
Replaced script with hardhat task in hardhat config

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by martinkersner — APPROVED** [review]
LGTM!

**Comment by nick-bisonai** [comment]
it's just an opinion, how about adding tasks to read public count variables? if you think it's unnecessary, that's okay. I thought it could be called after calling add or remove functions to check if the count has changed.

**Review by nick-bisonai — APPROVED** [review]
lgtm!

**Comment by KelvinThai** [comment]
> it's just an opinion, how about adding tasks to read public count variables? if you think it's unnecessary, that's okay. I thought it could be called after calling add or remove functions to check if the count has changed.

I think it's good to have, but then it should be consistent among all other tasks. Let's create another issue for that. I'll merge this PR for now

**Pull request merged**
