### PR TITLE
777 registry for vrf service on l2

### PR DESCRIPTION
**Pull request by KelvinThai**
# Description

This PR implements Registry and L1 endpoint for L2 VRF consumers
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

## Deployment

- [x] Should publish npm package

### CODE REVIEW

**Comment by bayram98** [comment]
@KelvinThai I am not sure if it related with your latest changes, but there are 2 failed tests. Could we try to fix them before merging the PR? 

https://github.com/Bisonai/orakl/actions/runs/5892717796/job/15982632417

**Comment by KelvinThai** [comment]
Yes, man. will check it today.

**Comment by KelvinThai** [comment]
Test case updated, please review it again @bayram98

**Review by bayram98 — APPROVED** [review]
LGTM! 🎉 

@KelvinThai  PR is looks good. 
Later, let's add documentation  with more detailed explanation about the logic on L2.

**Pull request merged**
