### PR TITLE
Use faster query to fetch the latest aggregate

### PR DESCRIPTION
**Pull request by martinkersner**
# Description

This PR replaces an autogenerated Prisma query with faster one for fetching the latest data aggregate given `aggregatorHash`.

The aggregated data are stored in `aggregates` table with one single column index on `aggregate_id` and multi-column index on `aggregator_id,"timestamp"DESC`. Since the goal of query is to fetch the *latest* aggregates given *aggregator hash*, we decided to optimize query rather than updating indexes.

Below you can see `AS-IS` and `TO-BE` versions of queries on table `data_ag_2023_11_04` (1.14M rows) seeking the latest aggregate value for `0xe87c49db104f27110170d10b10505220f0436fcdeb98754c076848903943fa89` aggregator hash. Five interleaving execution of queries have been conducted. Execution times for respective queries are shown below. The improvement in execution time is up to 6x.

| AS-IS | TO-BE |
|-------|--------|
| 417 | 96 |
| 338 | 97 | 
| 185 | 94 |
| 527 | 97 |
| 579 | 95 |

### AS-IS

```sql
SELECT
  "public"."data_ag_2023_11_04"."aggregate_id",
  "public"."data_ag_2023_11_04"."timestamp",
  "public"."data_ag_2023_11_04"."value",
  "public"."data_ag_2023_11_04"."aggregator_id"
FROM
  "public"."data_ag_2023_11_04"
WHERE
  ("public"."data_ag_2023_11_04"."aggregate_id") IN (
  SELECT
    "t0"."aggregate_id"
  FROM
    "public"."data_ag_2023_11_04" AS "t0"
  INNER JOIN
    "public"."aggregators" AS "j0"
  ON
    ("j0"."aggregator_id") = ("t0"."aggregator_id")
  WHERE
    ("j0"."aggregator_hash" = '0xe87c49db104f27110170d10b10505220f0436fcdeb98754c076848903943fa89'
      AND "t0"."aggregate_id" IS NOT NULL))
ORDER BY
  "public"."data_ag_2023_11_04"."timestamp" DESC
LIMIT
  1;
```

### TO-BE

```sql
SELECT
  aggregate_id, timestamp, value, aggregator_id
FROM data_ag_2023_11_04
WHERE aggregator_id = (
   SELECT aggregator_id FROM aggregators WHERE aggregator_hash = '0xe87c49db104f27110170d10b10505220f0436fcdeb98754c076848903943fa89')
ORDER BY timestamp DESC
LIMIT 1;
```

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by martinkersner** [comment]
Other option is to use newer version of Prisma 🤔 

https://github.com/prisma/prisma-engines/pull/3882

**Review by nick-bisonai — APPROVED** [review]
lgtm! maybe updating prisma version could be done from further pr?

**Review by bayram98 — APPROVED** [review]
LGTM!

**Comment by martinkersner** [comment]
> lgtm! maybe updating prisma version could be done from further pr?

@nick-bisonai Updating prisma is quite risky thing to do. I think we can do it later. Now, we should focus on other more important things.

**Pull request merged**
