### PR TITLE
Adjust core imports to new contracts package

### LINKED ISSUE #1472: fix issues in core package & add readme to contracts package
- After contracts package has been deployed to include versions, we need to update all the imports that reference @bisonai/orakl-contracts to include version. All those references happen in the core package
- rename logger.info to logger.debug
- ~~contracts package doesn't have readme~~
- ~~add lint-staged to core~~

### PR DESCRIPTION
**Pull request by Intizar-T**
# Description

- add /v0.1 to all contracts package imports in core
- replace logger.info to logger.debug
- Remove insufficient funds test from reporter test

Closes #1472 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Comment by Intizar-T** [comment]
> I think there should be some updates in package.json command where it runs command based on 'yarn contract' to 'yarn contract-v01'. since it runs both v0.1 and v0.2 codes, github action fails from point where it requires foundry(forge).
> 
> I saw one from prebuild script command but there could be more

I was planning to add foundry/forge installation to the workflow. I thought we might need both versions installed? or no need for v02?

**Comment by nick-bisonai** [comment]
> > I think there should be some updates in package.json command where it runs command based on 'yarn contract' to 'yarn contract-v01'. since it runs both v0.1 and v0.2 codes, github action fails from point where it requires foundry(forge).
> > I saw one from prebuild script command but there could be more
> 
> I was planning to add foundry/forge installation to the workflow. I thought we might need both versions installed? or no need for v02?

it's up to you, I don't mind, but since core package  only utilize v01 contracts. I thought It was okay to just reference v01 packages.

**Comment by Intizar-T** [comment]
> > > I think there should be some updates in package.json command where it runs command based on 'yarn contract' to 'yarn contract-v01'. since it runs both v0.1 and v0.2 codes, github action fails from point where it requires foundry(forge).
> > > I saw one from prebuild script command but there could be more
> > 
> > 
> > I was planning to add foundry/forge installation to the workflow. I thought we might need both versions installed? or no need for v02?
> 
> it's up to you, I don't mind, but since core package only utilize v01 contracts. I thought It was okay to just reference v01 packages.

Seems like just updating the package json is much easier than updating the workflow and dockerfiles haha

**Comment by nick-bisonai** [comment]
> > > > I think there should be some updates in package.json command where it runs command based on 'yarn contract' to 'yarn contract-v01'. since it runs both v0.1 and v0.2 codes, github action fails from point where it requires foundry(forge).
> > > > I saw one from prebuild script command but there could be more
> > > 
> > > 
> > > I was planning to add foundry/forge installation to the workflow. I thought we might need both versions installed? or no need for v02?
> > 
> > 
> > it's up to you, I don't mind, but since core package only utilize v01 contracts. I thought It was okay to just reference v01 packages.
> 
> Seems like just updating the package json is much easier than updating the workflow and dockerfiles haha

i agree

**Review by nick-bisonai — APPROVED** [review]
LGTM!

**Pull request merged**
