### PR TITLE
(OraklNode) Add accumulator condition

### PR DESCRIPTION
**Pull request by nick-bisonai**
# Description

Add condition to prevent overwriting redis database with old local aggregate data.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [x] Should publish Docker image

### CODE REVIEW

**Comment by Intizar-T** [comment]
hmm i cannot think of a scenario where this could happen. There is only one goroutine that handles a specific feed data. Data is popped from a channel and written to a db atomically. Is there any race condition that can result in outdated data?

**Comment by nick-bisonai** [comment]
> hmm i cannot think of a scenario where this could happen. There is only one goroutine that handles a specific feed data. Data is popped from a channel and written to a db atomically. Is there any race condition that can result in outdated data?

in redis, only single entry is stored per configuration id to be referenced from aggregator
from accumulator, if there's more than two more entries with the same configid, there's a possible scenario where the old local aggregate value overwrites new local aggregate value.

**Comment by Intizar-T** [comment]
> > hmm i cannot think of a scenario where this could happen. There is only one goroutine that handles a specific feed data. Data is popped from a channel and written to a db atomically. Is there any race condition that can result in outdated data?
> 
> in redis, only single entry is stored per configuration id as latest local aggregate value to be referenced from aggregator from accumulator, if there's more than two more entries with the same configid, there's a possible scenario where the old local aggregate value overwrites new local aggregate value.

hmm but keys in redis are unique so we cannot have multiple entries with the same configid, right?

**Comment by nick-bisonai** [comment]
> > > hmm i cannot think of a scenario where this could happen. There is only one goroutine that handles a specific feed data. Data is popped from a channel and written to a db atomically. Is there any race condition that can result in outdated data?
> > 
> > 
> > in redis, only single entry is stored per configuration id as latest local aggregate value to be referenced from aggregator from accumulator, if there's more than two more entries with the same configid, there's a possible scenario where the old local aggregate value overwrites new local aggregate value.
> 
> hmm but keys in redis are unique so we cannot have multiple entries with the same configid, right?

yes, that is why I added the condition, so that it doesn't overwrite with old data

**Pull request merged**
