### PR TITLE
(OraklNode) Add encrypt & decrypt util functions

### PR DESCRIPTION
**Pull request by nick-bisonai**
# Description

The feature is same as implemented from api.

`libp2p` nodes exchange messages based on topic string, this base utility functions will be used to encrypt the message topic.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Review by KelvinThai — APPROVED** [review]
LGTM!

**Comment by martinkersner** [comment]
@nick-bisonai I think I don't understand the point of the message encryption. If the goal is to secure message transfer so that potential malicious eavesdropper cannot understand or modify the message, then you have to also consider the first part of every multiparty secure communication which is key distribution.

**Comment by nick-bisonai** [comment]
> > > @nick-bisonai I think I don't understand the point of the message encryption. If the goal is to secure message transfer so that potential malicious eavesdropper cannot understand or modify the message, then you have to also consider the first part of every multiparty secure communication which is key distribution.
> > 
> > 
> > this is not to encrypt message itself, it will be used to encrypt topic string, so even if topic string is public in code, malicious player can't join as gossipsub peers
> 
> Got it! How do you plan to coordinate the exchange of the key between nodes?

I don't have plans yet, it's not required for q1 milestone so I'll think about it with more time

**Comment by martinkersner** [comment]
Okay! I think it will be easier to have a bootnode which holds all permissioned nodes that can participate as oracles, rather than figuring out how to hide the topic string.

**Comment by nick-bisonai** [comment]
> Okay! I think it will be easier to have a bootnode which holds all permissioned nodes that can participate as oracles, rather than figuring out how to hide the topic string.

in gossipsub, topic string is not used for connecting peers to other peers, but it works as endpoint for publishing and subscribing messages. if it is not hidden, we can't stop malicious players from sending unexpected messages to the channel.

**Pull request merged**
