### PR TITLE
Contracts v0.2 Baobab deployment

### PR DESCRIPTION
**Pull request by martinkersner**
# Description

* Deployment script using migration for `SubmissionProxy` + `Feed`s
* Updated README.md for contracts (v0.1 and v0.2)
* Deployed to Baobab (`0x260836ac4f046b6887bbe16b322e7f1e5f9a0452` can submit to submission Proxy)

| Contract | Address |
|---|---|
|  SubmissionProxy |0x47ff979f01FC2a6748560ef973d3AA2f8EeAe77c |
|  BTC-USDT | 0x4d649b215F359501c6efCECf07b71C67eCcCA4b5 |
|  ETH-USDT | 0x884343ABA9beDB0e7A5101C6A169C7aa842A5E00 |

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Summary by CodeRabbit

- **Documentation**
	- Updated the README files across versions to reflect new functionalities, corrected typos, and provided clearer instructions for deployment.
	- Provided updated links for conflict resolution and package dependency adjustments.

- **Chores**
	- Removed outdated configurations from the `.env.example` file.
	- Updated `.gitignore` patterns to better manage ignored files and directories.

- **Refactor**
	- Renamed `SubmissionProxyScript` to `DeploySubmissionProxy`.
	- Updated struct and function names for clarity and better functionality in script files.
	- Adjusted import paths and variable names in test files for consistency.

- **New Features**
	- Introduced a `DeployFull` contract for more efficient deployment and management of smart contracts, including functions for migrations, feed management, and submission proxies.

### CODE REVIEW

**Comment by martinkersner** [comment]
@coderabbit write a poem about this PR

**Comment by martinkersner** [comment]
> lgtm! btw, where did stack too deep err happen?

In the deployment script. The logic of `buildFeed` function was inside of th `run` function, but after separating it, it went away. There is a limit on how many local variables you can store in stack, so in more complicated projects, this happens all the time.

**Comment by nick-bisonai** [comment]
> @CodeRabbit write a poem about this PR

it's in the first comment made by rabbit ☺️

**Comment by martinkersner** [comment]
> > @CodeRabbit write a poem about this PR
> 
> it's in the first comment made by rabbit ☺️

I saw it, but I wanted something more specific about this PR content. About dangers of Solidity and bravery of developers using Solidity :D

**Pull request merged**
