### PR TITLE
reporter dockerfile and deployment workflow

### PR DESCRIPTION
**Pull request by Intizar-T**
# Description

Please include a summary of the changes and the related issue.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

**Comment by nick-bisonai** [comment]
I just found out that it doesn't have pgsql migration step in the file 🤔
it should imply that it isn't utilizing node db nor using its own db I think.

is the only part where db is called as followed? or are there more places where pgsql is used?
```
func getConfigs(ctx context.Context) ([]Config, error) {
	reporterConfigs, err := db.QueryRows[Config](ctx, GET_REPORTER_CONFIGS, nil)
	if err != nil {
		log.Error().Str("Player", "Reporter").Err(err).Msg("failed to load reporter configs")
		return nil, err
	}
	return reporterConfigs, nil
}
```

**Comment by Intizar-T** [comment]
> I just found out that it doesn't have pgsql migration step in the file 🤔 it should imply that it isn't utilizing node db nor using its own db I think.
> 
> is the only part where db is called as followed? or are there more places where pgsql is used?
> 
> ```
> func getConfigs(ctx context.Context) ([]Config, error) {
> 	reporterConfigs, err := db.QueryRows[Config](ctx, GET_REPORTER_CONFIGS, nil)
> 	if err != nil {
> 		log.Error().Str("Player", "Reporter").Err(err).Msg("failed to load reporter configs")
> 		return nil, err
> 	}
> 	return reporterConfigs, nil
> }
> ```

Ah good point. That's the only point where node db is accessed. We just need to provide `DATABASE_URL` during build right?

**Comment by nick-bisonai** [comment]
no during the build `DATABASE_URL` is not required, but if it is using node db it could lead to problem later. 
migrations are done separately from node service yet if reporter keeps accessing the db there could be a unintentional conflict. In that sense, I also tried to separate db for dal and boot api.

**Comment by Intizar-T** [comment]
> no during the build, `DATABASE_URL` is not required, but if it is using node db it could lead to problem later. migrations are done separately from node service yet if reporter keeps accessing the db there could be a unintentional conflict. In that sense, I also tried to separate db for dal and boot api.

ah in that case i think it's better to simply fetch configs from the public endpoint and construct the []Config objects. That way the reporter wont depend on any db. What do you think?

**Comment by nick-bisonai** [comment]
> > no during the build, `DATABASE_URL` is not required, but if it is using node db it could lead to problem later. migrations are done separately from node service yet if reporter keeps accessing the db there could be a unintentional conflict. In that sense, I also tried to separate db for dal and boot api.
> 
> ah in that case i think it's better to simply fetch configs from the public endpoint and construct the []Config objects. That way the reporter wont depend on any db. What do you think?

public endpoint is also okay, you mean orakl.network right?

**Comment by Intizar-T** [comment]
> > > no during the build, `DATABASE_URL` is not required, but if it is using node db it could lead to problem later. migrations are done separately from node service yet if reporter keeps accessing the db there could be a unintentional conflict. In that sense, I also tried to separate db for dal and boot api.
> > 
> > 
> > ah in that case i think it's better to simply fetch configs from the public endpoint and construct the []Config objects. That way the reporter wont depend on any db. What do you think?
> 
> public endpoint is also okay, you mean orakl.network right?

yes these endpoints `https://config.orakl.network/baobab_configs.json` and `https://config.orakl.network/cypress_configs.json`

**Review by nick-bisonai — APPROVED** [review]
I think the it is mostly okay, let's keep this pr opened until the code has been merged

**Pull request merged**
